version: '3'
services:
  db_aws:
    image: postgres:14-alpine
    volumes:
      - db_aws:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aws_password
  web:
    build: .
    image: aws_rails_app:latest
    command: bundle exec rails s -p 3100 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle_aws:/usr/local/bundle
      - node_modules_aws:/myapp/node_modules
    ports:
      - "3100:3100"
    depends_on:
      - db_aws
  js:
    image: aws_rails_app:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle_aws:/usr/local/bundle
      - node_modules_aws:/myapp/node_modules
    tty: true
  css:
    image: aws_rails_app:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle_aws:/usr/local/bundle
      - node_modules_aws:/myapp/node_modules
    tty: true
volumes:
  db_aws:
  bundle_aws:
  node_modules_aws:
